# site settings
title: Portfolio
email: mrozsypal81@gmail.com
description: A collection of all projects done by Michael
baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
#author:
#street_address: 1234 Somewhere Road
city: Fullerton
state: CA
#zip_code: 55555
country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
#500px_url:
#facebook_url:
github_url: https://github.com/mrozsypal81
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/mrozsypal/
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
